# Site settings
title: 99Taxis
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
copyright_name: 99Taxis Engineering
description: "Write your site description here. It will be used as your sites meta description as well!"
url: "http://dev.99taxis.com"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

# Authors
authors:
  fbenevides:
    name: Felipe Benevides
    display_name: Felipe Benevides
    email: felipe.benevides@99taxis.com
    github: http://github.com/fbenevides
  dabramovici:
    name: Daniel Abramovici
    display_name: Daniel Abramovici
    email: daniel@99taxis.com
    github: http://github.com/dabramovici
